#!/usr/bin/env python3
"""Mirror connector: keeps a folder that already lives on this Mac in sync
with the brain, and turns the parts of it graphify cannot read into Markdown.

Generated by `brain new-connector <project> <name> --mirror <folder>` (and by
`brain new` when you point it at a local folder). Unlike the generic template,
this one is complete — there is no fetch_records() to fill in.

Why a copy and not a symlink: graphify does not follow symlinks (detect.py,
follow_symlinks=False, no CLI flag), so a linked folder would simply never be
indexed. rsync --delete makes the copy idempotent — files removed at the source
disappear from the brain on the next sync instead of lingering as stale nodes.

Why a conversion step as well: graphify indexes .md/.txt/.rst/.html/.yaml,
.pdf, images and .docx/.xlsx by itself, and silently ignores everything else.
A real folder is full of everything else — a CSV export, a JSON dump — and
those were being copied into the brain and skipped without a word, so the brain
looked full while the graph was nearly empty. Tables and JSON are turned into
the same Markdown-plus-frontmatter records every other connector writes. What
still cannot be read (a .numbers, a .key, a video) is named in the summary
rather than left for you to discover from a graph that is missing half its
subject matter.

Contract with `brain sync` is the same as any other connector: accept
--out <dir>, exit 0/non-zero, print a human-readable summary.
"""
from __future__ import annotations

import argparse
import csv
import json
import subprocess
import sys
from pathlib import Path

from brainiphy_cli.frontmatter import write_record

SOURCE_SYSTEM = 'mirror'
MIRROR_SOURCE = None

# Noise that would otherwise become graph nodes. Extend this list freely — it
# is a plain rsync --exclude list, this file is yours once generated.
EXCLUDES = [
    ".DS_Store",
    ".git/",
    "node_modules/",
    "__pycache__/",
    "*.tmp",
]

# What graphify reads on its own (detect.py). These are copied and left alone:
# converting them would only put a worse version of the file in the graph.
NATIVE_EXTENSIONS = {
    ".md", ".mdx", ".qmd", ".skill", ".txt", ".rst", ".html", ".yaml", ".yml",
    ".pdf",
    ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg",
    ".docx", ".xlsx",
}

# What this connector can turn into records. Everything else is reported.
TABLE_EXTENSIONS = {".csv", ".tsv"}
JSON_EXTENSIONS = {".json"}

# One record per row, so the graph gets entities rather than one node holding a
# table. A cap because a 200k-row export would otherwise bury every other
# source in the brain; when it bites, the summary says so.
MAX_ROWS_PER_TABLE = 500

# Converted records live here, under --out. Kept out of the rsync so that
# --delete does not remove them again on the next run: they have no counterpart
# in the source folder, which is exactly what --delete deletes.
DERIVED_DIRNAME = "_converted"


def field_name(raw: str, position: int) -> str:
    """A CSV header turned into something usable as a YAML key.

    Headers in the wild are 'Importe (€)' and 'Fecha de alta'. Left as they
    are, they produce frontmatter nobody can query and, worse, keys that a
    parser reads as something other than a key.
    """
    cleaned = "".join(ch if ch.isalnum() else "_" for ch in (raw or "").strip().lower())
    cleaned = "_".join(part for part in cleaned.split("_") if part)
    return cleaned or f"column_{position + 1}"


def _row_title(row: dict, fallback: str) -> str:
    """The first value that looks like a name, else something identifiable.

    The title is what the record is called in the graph, so 'acme' beats
    'row 12' by a distance.
    """
    for key in ("name", "title", "nombre", "cliente", "client", "company",
                "empresa", "email", "id"):
        value = row.get(key)
        if value and str(value).strip():
            return str(value).strip()
    for value in row.values():
        if value and str(value).strip():
            return str(value).strip()[:80]
    return fallback


def _body(row: dict) -> str:
    """A labelled list, not a JSON dump: a model reads these files to build the
    graph, and prose-shaped input gives it more to work with."""
    lines = []
    for key, value in row.items():
        if value in (None, "", [], {}):
            continue
        if isinstance(value, (list, dict)):
            value = json.dumps(value, ensure_ascii=False)
        lines.append(f"- **{key}**: {value}")
    return "\n".join(lines) or "(empty record)"


def records_from_table(path: Path) -> tuple[list[dict], bool]:
    """One record per row. Returns (records, whether the cap was hit)."""
    delimiter = "\t" if path.suffix.lower() == ".tsv" else ","
    records: list[dict] = []
    capped = False
    with path.open(newline="", encoding="utf-8", errors="replace") as handle:
        reader = csv.reader(handle, delimiter=delimiter)
        try:
            header = next(reader)
        except StopIteration:
            return [], False
        names = [field_name(name, index) for index, name in enumerate(header)]
        for index, raw_row in enumerate(reader, start=1):
            if index > MAX_ROWS_PER_TABLE:
                capped = True
                break
            if not any(cell.strip() for cell in raw_row):
                continue
            row = {names[i]: cell for i, cell in enumerate(raw_row) if i < len(names)}
            records.append({
                "id": f"{path.name}:{index}",
                "title": _row_title(row, f"{path.stem} row {index}"),
                "fields": row,
            })
    return records, capped


def records_from_json(path: Path) -> tuple[list[dict], bool]:
    """A list of objects becomes one record each; anything else, one record."""
    try:
        data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except (json.JSONDecodeError, OSError):
        return [], False

    if isinstance(data, list):
        rows = [item for item in data if isinstance(item, dict)]
        capped = len(rows) > MAX_ROWS_PER_TABLE
        rows = rows[:MAX_ROWS_PER_TABLE]
        return ([
            {
                "id": f"{path.name}:{index}",
                "title": _row_title(row, f"{path.stem} item {index}"),
                "fields": row,
            }
            for index, row in enumerate(rows, start=1)
        ], capped)

    if isinstance(data, dict):
        return ([{"id": path.name, "title": path.stem, "fields": data}], False)
    return [], False


def convert(path: Path, out_dir: Path, relative: Path) -> tuple[int, bool]:
    """Write one file's records under out_dir. Returns (written, capped)."""
    suffix = path.suffix.lower()
    if suffix in TABLE_EXTENSIONS:
        records, capped = records_from_table(path)
    elif suffix in JSON_EXTENSIONS:
        records, capped = records_from_json(path)
    else:
        return 0, False

    target = out_dir / relative.parent / relative.stem
    for record in records:
        write_record(
            target,
            record_id=record["id"],
            title=record["title"],
            body=_body(record["fields"]),
            source_system=SOURCE_SYSTEM,
            extra_fields={"source_file": str(relative), **{
                key: value for key, value in record["fields"].items()
                if not isinstance(value, (list, dict))
            }},
        )
    return len(records), capped


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    source = Path(MIRROR_SOURCE).expanduser()
    if not source.is_dir():
        print(f"[{SOURCE_SYSTEM}] source folder is gone: {source}", file=sys.stderr)
        return 1

    args.out.mkdir(parents=True, exist_ok=True)
    derived = args.out / DERIVED_DIRNAME

    # Trailing slashes matter: "src/" copies the *contents* of src into out,
    # rather than nesting a src/ folder inside it on every run.
    cmd = ["rsync", "-a", "--delete", "--exclude", f"{DERIVED_DIRNAME}/"]
    for pattern in EXCLUDES:
        cmd += ["--exclude", pattern]
    cmd += [f"{source}/", f"{args.out}/"]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stderr.rstrip(), file=sys.stderr)
        print(f"[{SOURCE_SYSTEM}] rsync failed (exit {result.returncode})", file=sys.stderr)
        return result.returncode

    # Rebuilt from scratch every run: a row deleted at the source has to stop
    # being a node, and there is no rsync --delete watching this folder.
    if derived.exists():
        for path in sorted(derived.rglob("*"), reverse=True):
            path.unlink() if path.is_file() else path.rmdir()

    native = converted = written = 0
    capped_files: list[str] = []
    unreadable: list[str] = []

    for path in sorted(args.out.rglob("*")):
        if not path.is_file() or derived in path.parents:
            continue
        relative = path.relative_to(args.out)
        suffix = path.suffix.lower()
        if suffix in NATIVE_EXTENSIONS:
            native += 1
        elif suffix in TABLE_EXTENSIONS or suffix in JSON_EXTENSIONS:
            count, capped = convert(path, derived, relative)
            if count:
                converted += 1
                written += count
            if capped:
                capped_files.append(str(relative))
        elif not path.name.startswith("."):
            unreadable.append(str(relative))

    print(f"[{SOURCE_SYSTEM}] mirrored {source} -> {args.out}")
    print(f"[{SOURCE_SYSTEM}] {native} file(s) graphify reads directly")
    if converted:
        print(f"[{SOURCE_SYSTEM}] {converted} file(s) converted into "
              f"{written} record(s) under {DERIVED_DIRNAME}/")
    for name in capped_files:
        print(f"[{SOURCE_SYSTEM}] {name}: only the first {MAX_ROWS_PER_TABLE} rows were "
              f"converted — raise MAX_ROWS_PER_TABLE in this script to take more")
    if unreadable:
        # The whole point of saying this: these files are in the brain's folder
        # and will never be in its graph, and nothing else would tell you.
        print(f"[{SOURCE_SYSTEM}] {len(unreadable)} file(s) cannot be indexed and were "
              f"skipped: {', '.join(sorted(unreadable)[:10])}"
              + (" …" if len(unreadable) > 10 else ""))
        print(f"[{SOURCE_SYSTEM}] export them as PDF, Markdown or CSV to bring them in")
    return 0


if __name__ == "__main__":
    sys.exit(main())
