#!/usr/bin/env python3
"""Mirror connector: keeps a folder that already lives on this Mac in sync
with the brain.

Generated by `brain new-connector <project> <name> --mirror <folder>` (and by
`brain new` when you point it at a local folder). Unlike the generic template,
this one is complete — there is no fetch_records() to fill in.

Why a copy and not a symlink: graphify does not follow symlinks (detect.py,
follow_symlinks=False, no CLI flag), so a linked folder would simply never be
indexed. rsync --delete makes the copy idempotent — files removed at the source
disappear from the brain on the next sync instead of lingering as stale nodes.

Contract with `brain sync` is the same as any other connector: accept
--out <dir>, exit 0/non-zero, print a human-readable summary.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

SOURCE_SYSTEM = "REPLACE_ME"
MIRROR_SOURCE = Path("REPLACE_ME_SOURCE")

# Noise that would otherwise become graph nodes. Extend this list freely — it
# is a plain rsync --exclude list, this file is yours once generated.
EXCLUDES = [
    ".DS_Store",
    ".git/",
    "node_modules/",
    "__pycache__/",
    "*.tmp",
]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    source = MIRROR_SOURCE.expanduser()
    if not source.is_dir():
        print(f"[{SOURCE_SYSTEM}] source folder is gone: {source}", file=sys.stderr)
        return 1

    args.out.mkdir(parents=True, exist_ok=True)

    # Trailing slashes matter: "src/" copies the *contents* of src into out,
    # rather than nesting a src/ folder inside it on every run.
    cmd = ["rsync", "-a", "--delete"]
    for pattern in EXCLUDES:
        cmd += ["--exclude", pattern]
    cmd += [f"{source}/", f"{args.out}/"]

    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stderr.rstrip(), file=sys.stderr)
        print(f"[{SOURCE_SYSTEM}] rsync failed (exit {result.returncode})", file=sys.stderr)
        return result.returncode

    file_count = sum(1 for p in args.out.rglob("*") if p.is_file())
    print(f"[{SOURCE_SYSTEM}] mirrored {source} -> {args.out} ({file_count} file(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
